name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      project-version:
        required: true
        type: string
      java-release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <mirrors>
              <mirror>
                <id>private-mirror</id>
                <url>${MAVEN_REPO_URL}</url>
                <mirrorOf>private</mirrorOf>
              </mirror>
            </mirrors>
            <servers>
              <server>
                <id>private-mirror</id>
                <username>${MAVEN_USERNAME}</username>
                <password>${MAVEN_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF
        env:
          MAVEN_REPO_URL: ${{ secrets.MAVEN_REPO_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Deploy with Maven
        run: |
          export DISPLAY=:90
          Xvfb -ac :90 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mvn -B -ntp -q versions:set -DnewVersion=${{ inputs.project-version }} -DgenerateBackupPoms=false
          mvn -B -ntp clean package
          mvn -B -ntp deploy -DskipTests -f kit

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SceneBuilder-${{ inputs.project-version }}
          path: |
            app/target/lib/scenebuilder-${{ inputs.project-version }}-all.jar
            kit/target/lib/scenebuilder-kit-${{ inputs.project-version }}.jar
