name: Build & Deploy

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      java-release:
        required: true
        type: string
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: oracle-actions/setup-java@v1.4.0
        with:
          website: jdk.java.net
          release: ${{ inputs.java-release }}
          version: ${{ inputs.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Deploy with Maven
        run: |
          export DISPLAY=:90
          Xvfb -ac :90 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mvn -B -ntp -q versions:set -DnewVersion=${{ inputs.project-version }} -DgenerateBackupPoms=false
          mvn -B -ntp clean package
          mvn -B -ntp deploy -Dmaven.test.skip=true -f kit

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SceneBuilder-${{ inputs.project-version }}
          path: |
            app/target/lib/scenebuilder-${{ inputs.project-version }}-all.jar
            kit/target/lib/scenebuilder-kit-${{ inputs.project-version }}.jar
